<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/hoctangcuong/bt5-22.03.23/tao_ham_day5_HoMinhTri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:
import numpy as np

In [139]:
V = np.zeros((3,4))

In [140]:
V
lock = [(1,1)]
done = [(0,3),(1,3),(2,0), (1,1)]

In [141]:
reward = 0

In [142]:
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  for l in lock:
    if l in true_list_move:
      true_list_move.remove(l)
  return true_list_move

In [144]:
moves = find_move(1,2, V.shape)

In [145]:
for l in lock:
  if l in moves:
    moves.remove(l)

In [146]:
moves

[(0, 2), (2, 2), (1, 3)]

In [147]:
V[1,3]=-1
V[0,3] = 1
V[1,1] = -100
gamma = 0.9

In [148]:
V

array([[   0.,    0.,    0.,    1.],
       [   0., -100.,    0.,   -1.],
       [   0.,    0.,    0.,    0.]])

In [149]:
moves_02 = find_move(0,2, V.shape)

In [150]:
moves_02

[(1, 2), (0, 1), (0, 3)]

In [151]:
def other_points(input_value, list_point):
    list_a = []
    if input_value in list_point:
        for item in list_point:
            if item != input_value:
                list_a.append(item)
    else:
        print("Giá trị nhập không hợp lệ.")
    return list_a

In [152]:
def update_value(moves):
  value_range = []
  for move in moves:
    position_other_points = other_points(move,moves)
    sum_other_points = 0
    for position in position_other_points:
      point = V[position]
      sum_other_points+=point
    value = 0.8*(reward + gamma*V[move]+(0.2/(len(moves)-1))*(2*reward + gamma*sum_other_points))
    value_range.append(value)
  return max(value_range)

In [153]:
for i in [1,2,3]:
  i +=i
  print(i)

2
4
6


In [154]:
for _ in range(5):
  for i, row in enumerate(V):
    #print(i)
    for j, _ in enumerate(row):
      if (i,j) not in done:
        moves = find_move(i,j, V.shape)
        V[i,j] = update_value(moves)

  print(V, "\n")

[[ 0.000000e+00  0.000000e+00  7.200000e-01  1.000000e+00]
 [ 0.000000e+00 -1.000000e+02  4.464000e-01 -1.000000e+00]
 [ 0.000000e+00  0.000000e+00  3.214080e-01  8.741376e-02]] 

[[   0.            0.5184        0.7894656     1.        ]
 [   0.         -100.            0.51955661   -1.        ]
 [   0.            0.23141376    0.39703634    0.14186616]] 

[[   0.373248      0.62216294    0.80220381    1.        ]
 [   0.26873856 -100.            0.53417336   -1.        ]
 [   0.            0.28586616    0.41540155    0.15508911]] 

[[   0.48665567    0.64766516    0.80509237    1.        ]
 [   0.35039208 -100.            0.53757542   -1.        ]
 [   0.            0.29908911    0.41975513    0.1582237 ]] 

[[   0.51677537    0.65408216    0.80579935    1.        ]
 [   0.37207827 -100.            0.5383979    -1.        ]
 [   0.            0.3022237     0.4207987     0.15897506]] 

