<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/hoctangcuong/bt5-22.03.23/tao_ham_day5_HoMinhTri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np

In [73]:
V = np.zeros((3,4))

In [74]:
V
lock = [(1,1)]

In [75]:
reward = 0

In [76]:
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  return true_list_move

In [78]:
moves = find_move(1,2, V.shape)

In [79]:
for l in lock:
  if l in moves:
    moves.remove(l)

In [80]:
moves

[(0, 2), (2, 2), (1, 3)]

In [82]:
V[1,3]=-1
V[0,3] = 1
V[1,1] = -100
gamma = 0.9

In [83]:
V

array([[   0.,    0.,    0.,    1.],
       [   0., -100.,    0.,   -1.],
       [   0.,    0.,    0.,    0.]])

In [87]:
moves_02 = find_move(0,2, V.shape)

In [92]:
list_a = [1,2,3]

In [103]:
def other_points(input_value, list_point):
    list_a = []
    if input_value in list_point:
        for item in list_point:
            if item != input_value:
                list_a.append(item)
    else:
        print("Giá trị nhập không hợp lệ.")
    return list_a

In [105]:
for move in moves_02:
  move_2, move_3 = other_points(move,moves_02)
  print(0.8*(reward + gamma*V[move]+(0.2/len(moves_02))*(2*reward + gamma*(V[move_2]+V[move_3]))))

0.048
0.048
0.7200000000000001


In [84]:
V[0,2] = max( 0.8*(reward + gamma*V[0,3] ) + 0.1*(reward + gamma*V[0,1]) + 0.1*(reward + gamma*V[1,2]),
              0.1*(reward + gamma*V[0,3] ) + 0.8*(reward + gamma*V[0,1]) + 0.1*(reward + gamma*V[1,2]),
              0.1*(reward + gamma*V[0,3] ) + 0.1*(reward + gamma*V[0,1]) + 0.8*(reward + gamma*V[1,2]))

In [85]:
V

array([[   0.  ,    0.  ,    0.72,    1.  ],
       [   0.  , -100.  ,    0.  ,   -1.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ]])