<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/deep_learning/bt_04_04_23/timhieu_pytorch_b3_04_04_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [30]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
X.shape

(4, 2)

In [31]:
torch_X = torch.from_numpy(X).float()
torch_X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [32]:
y_z1 = np.logical_and(X[:,0], np.logical_not(X[:,1]))
y_z2 = np.logical_and(np.logical_not(X[:,0]), X[:,1])

torch_y_z1 = torch.from_numpy(y_z1).float().view(-1, 1)
torch_y_z2 = torch.from_numpy(y_z2).float().view(-1, 1)

z = np.array([y_z1,y_z2]).T
torch_z = torch.from_numpy(z).float()
torch_z

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [0., 0.]])

In [33]:
print(torch_y_z1,"\n",torch_y_z2)

tensor([[0.],
        [0.],
        [1.],
        [0.]]) 
 tensor([[0.],
        [1.],
        [0.],
        [0.]])


In [34]:
y = np.logical_or(y_z1, y_z2)
torch_y = torch.from_numpy(y).float().view(-1, 1)

In [35]:
w_x1 = torch.ones(2)
w_x2 = torch.ones(2)
w_z = torch.ones(2)

In [36]:
w_x1

tensor([1., 1.])

In [37]:
#z1 = x1 * -x2
"""
z1
  0
  0
  1
  0
"""
#z2 = -x1 * x2
"""
z2
  0
  1
  0
  0
"""

'\nz2\n  0\n  1\n  0\n  0\n'

In [38]:
x1_with_not_x2 = np.array([X[:,0], np.logical_not(X[:,1])]).T
print(x1_with_not_x2,"\n")

not_x1_with_x2 = np.array([np.logical_not(X[:,0]), X[:,1]]).T
print(not_x1_with_x2)

[[0 1]
 [0 0]
 [1 1]
 [1 0]] 

[[1 0]
 [1 1]
 [0 0]
 [0 1]]


In [40]:
torch_x1_with_not_x2 = torch.from_numpy(x1_with_not_x2).float()
torch_not_x1_with_x2 = torch.from_numpy(not_x1_with_x2).float()

In [41]:
def tinh_toan(value):
  if value >= 1:
    return 1
  else:
    return 0

In [42]:
lr = 0.5

w = w+ lr(y-y_pred)*x

In [43]:
def update(w, x, y_z):
  for time in range(10):
    for i in range(4):
      z = w.T@x[i]
      if (tinh_toan(z) == y_z[i]):
        print("true")
      else:
        w = w + lr*(y_z[i]- tinh_toan(z))*x[i]
        print("sai")
        break

  return w

In [44]:
#w_x1
update(w_x1,torch_x1_with_not_x2,torch_y_z1)

sai
true
true
true
sai
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true


tensor([0.5000, 0.5000])

In [45]:
#w_x2
update(w_x2,torch_not_x1_with_x2,torch_y_z2)

sai
true
true
true
sai
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true


tensor([0.5000, 0.5000])

In [46]:
#w_z
update(w_z,torch_z,torch_y)

true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true


tensor([1., 1.])