In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def veG(list1, list2):
  print(f'{list1[0]}-------{list1[1]}')
  for i in range(4):
    print('  '*i,'\\')
  print(f'{list1[2]}-------{list1[3]}')

In [ ]:
veG(('a','b','c','d'),())

a-------b
 \
   \
     \
       \
c-------d


In [ ]:
def veNgangTren():
  for i in range(1,4):
    df[i][0] = '-'
veNgangTren()
def veNgangDuoi():
  for i in range(1,4):
    df[i][4] = '-'
veNgangDuoi()

In [ ]:
def veCheoPhaiTrai():
  j = 1
  for i in reversed(range(1,4)):
      df[i][j] = "/"
      j +=1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [ ]:
def veCheoTraiPhai():
    for i in reversed(range(1,4)):
        df[i][i] = "\\"

In [ ]:
def veDuongThangXuongTrai():
  for i in range(1,4):
    df[0][i] = "|"
def veDuongThangXuongPhai():
  for i in range(1,4):
    df[4][i] = "|"
veDuongThangXuongPhai()

In [ ]:
A = np.zeros( (5, 5) )

In [ ]:
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(A)

[[1. 0. 0. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [3. 0. 0. 4.]]


In [ ]:
df = pd.DataFrame(data=A)
df

0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

In [ ]:
df[0][0] = "A"
df[4][0] = "B"
df[4][4] = "C"
df[0][4] = "D"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid d

In [ ]:
df

0  1  2  3  4
0  A  0  0  0  B
1  |  \  0  /  0
2  |  0  \  0  0
3  |  /  0  \  0
4  D  0  0  0  C

In [ ]:
lien_ket = {("A","B"),("B","C"),("C","D"),("B","D"),("D","D")}
lien_ket

{('A', 'B'), ('B', 'C'), ('B', 'D'), ('C', 'D'), ('D', 'D')}

In [ ]:
if ("A","C") in lien_ket:
  veCheoTraiPhai()
if ("A","B") in lien_ket:
  veNgangTren()
if ("B","C") in lien_ket:
  veDuongThangXuongPhai()
if ("C","D") in lien_ket:
  veNgangDuoi()
if ("B","D") in lien_ket:
  veCheoPhaiTrai()
if ("A","D") in lien_ket:
  veDuongThangXuongTrai()
if ("A","C") in lien_ket:
  veCheoTraiPhai()


In [ ]:
df

0  1  2  3  4
0  A  -  -  -  B
1  0  0  0  /  |
2  0  0  /  0  |
3  0  /  0  0  |
4  D  -  -  -  C