<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/deep_learning/bt_21_3_24_day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

arr = np.array([
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]])
print(arr)

[[1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


In [40]:
theta = 0
la = 1.5

In [41]:
y = np.zeros(8, int)
y[-1] = 1

In [42]:
y

array([0, 0, 0, 0, 0, 0, 0, 1])

In [43]:
w = np.array([1,1,1,1])

In [44]:
w.T@arr[0]

1

In [45]:
arr[1]

array([1, 0, 0, 1])

In [46]:
done = False
while not done:
  for stt, x in enumerate(arr):
    y_h = w.T@x
    if y_h >= theta:
      y_hat = 1
    else:
      y_hat = 0
    if y_hat == y[stt]:
      print("true")
    else:
      for i, w_i in enumerate(w):
        w_i = w_i - la*(y_hat-y[stt])*x[i]
        w[i] = w_i
        done = False
        break
    if stt == 7:
      done = True

true
true
true
true


In [47]:
w

array([-3,  1,  1,  1])