<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/deep_learning/bt_21_3_24_day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]])
print(arr)

[[1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


In [3]:
theta = 1.0
la = 1.0

In [4]:
y = np.zeros(8, int)
y[-1] = 1

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1])

In [18]:
w = np.array([1,1,1,1])

In [19]:
w.T@arr[0]

1

In [20]:
arr[1]

array([1, 0, 0, 1])

In [21]:
while 1:
  count = 0
  for stt, x in enumerate(arr):
    y_h = w.T@x
    if y_h >= theta:
      y_hat = 1
      print(y[stt],"so voi" ,y_hat)
    else:
      y_hat = 0
      print(y[stt],"so voi" ,y_hat)
    if y_hat == y[stt]:
      count+=1
      pass
    else:
      for i, w_i in enumerate(w):
        w_i = w_i - la*(y_hat-y[stt])*x[i]
        w[i] = w_i
      break
  if count ==8:
    break

0 so voi 1
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
1 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
1 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
1 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
1 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 1
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
0 so voi 0
1 so voi 1


In [22]:
w

array([-3,  2,  1,  1])

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 1])

In [24]:
w

array([-3,  2,  1,  1])

In [25]:
for stt, x in enumerate(arr):
    print(w.T@x)

-3
-2
-2
-1
-1
0
0
1
