<a href="https://colab.research.google.com/github/eggtgg/bt_minhtriho_all/blob/main/hoctangcuong/bt_th_2_5_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

V(st)  <-- V(st) + alpha *( R(t+1)  + gamma * V(st+1) - V(st))

In [58]:
import numpy as np
import pandas as pd
import random

In [9]:
q_table =  np.zeros([3,4,4])
q_table

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
q_table

(3,)

In [10]:
dict_acts = {
    0: "^",
    1:"v",
    2:"<",
    3: ">"
}

In [12]:
list_act_move = {
    0: np.array([-1,0]),
    1: np.array([1,0]),
    2: np.array([0, -1]),
    3: np.array([0, 1])
}

In [17]:
grid = np.zeros([3,4])
grid

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
walls = np.array([1,1]), np.array([2,3])

In [53]:
target = np.array([0,3])

In [50]:
for w in walls:
  print(w)

[1 1]
[2 3]


In [51]:
for w in walls:
  grid[w[0], w[1]] = -1

In [54]:
grid[target[0], target[1]] = 1

In [55]:
grid

array([[ 0.,  0.,  0.,  1.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.]])

In [56]:
tom = np.array([2,0])

In [ ]:
def tom_move(way):
  tom += way

In [132]:
root_car = np.array([2,0])

In [137]:
class CarGame:
  def __init__(self, grid, q_table):
    self.car = np.array([2,0])
    self.grid = grid
    self.q_table = q_table
    self.alpha = 0.1
    self.gamma = 0.9

    #self.root_car = np.array([2,0])
    self.root_grid = grid
    self.root_q_table = q_table

  def car_move(self, way):
    self.car += list_act_move[way]
    print(f"car da den o {self.car}")

  def end_game_checker(self):
    if self.car[0] <0  or self.car[1] <0:
      end_game = True
    elif (self.car[0]+1) > self.grid.shape[0] or (self.car[1]+1) > self.grid.shape[1]:
      end_game = True
    elif grid[self.car[0], self.car[1]] == -1:
      end_game = True
    else:
      end_game = False
    return end_game

  def random_move(self):
    way = random.randint(0,3)
    old_car = self.car
    self.car_move(way)
    check_end = self.end_game_checker()
    if check_end:
      q_table[old_car[0], old_car[1], way] = q_table[old_car[0], old_car[1], way] + self.alpha *(-1 + self.gamma* (-1) - q_table[old_car[0], old_car[1], way])
      self.car = np.array([2,0])
    else:
      q_table[old_car[0], old_car[1], way] = q_table[old_car[0], old_car[1], way] + self.alpha *(grid[self.car[0], self.car[1]] + self.gamma* q_table[self.car[0], self.car[0], way] - q_table[old_car[0], old_car[1], way])


  def q_move(self, way):
    old_car = self.car
    self.car_move(way)
    check_end = self.end_game_checker()
    if check_end:
      q_table[old_car[0], old_car[1], way] = q_table[old_car[0], old_car[1], way] + self.alpha *(-1 + self.gamma* (-1) - q_table[old_car[0], old_car[1], way])
      self.car = np.array([2,0])
    else:
      q_table[old_car[0], old_car[1], way] = q_table[old_car[0], old_car[1], way] + self.alpha *(grid[self.car[0], self.car[1]] + self.gamma* q_table[self.car[0], self.car[0], way] - q_table[old_car[0], old_car[1], way])





In [146]:
Game  = CarGame(grid, q_table)

In [150]:
Game.grid.shape[0]

3

In [152]:
Game.car

array([3, 1])

In [147]:
for i in range(1000):
  rd = random.randint(0,1000)
  if rd >= 800:
    max_way = np.argmax(Game.q_table[Game.car[0],Game.car[0]])
    Game.q_move(max_way)
  else:
    Game.random_move()

car da den o [1 0]
car da den o [1 1]
car da den o [1 0]
car da den o [0 0]
car da den o [ 0 -1]
car da den o [2 1]
car da den o [2 0]
car da den o [1 0]
car da den o [ 1 -1]
car da den o [1 0]
car da den o [ 1 -1]
car da den o [ 2 -1]
car da den o [2 1]
car da den o [3 1]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [144]:
np.array([2,0])

array([2, 0])

In [136]:
root_car

array([-2, -5])

In [131]:
Game.root_car

array([ 1, -5])

In [103]:
Game.car

array([-4,  0])

In [99]:
Game.q_table

array([[[ 0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -0.1 ,  0.  ],
        [-0.19,  0.  ,  0.  , -0.1 ]],

       [[ 0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.1 ],
        [ 0.  ,  0.  ,  0.  ,  0.  ],
        [-0.19,  0.  ,  0.  ,  0.  ]],

       [[ 0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ],
        [-0.1 ,  0.  , -0.1 ,  0.  ]]])

In [91]:
max_way

0

In [86]:
np.argmax(Game.q_table[Game.car[0],Game.car[0]])

0

In [80]:
max(1,2)

2

In [60]:
grid.shape[0]

3